// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Cat struct {
	CatID       int32       `json:"cat_id"`
	Name        string      `json:"name"`
	Age         int32       `json:"age"`
	Description pgtype.Text `json:"description"`
}
